name: Generate Uniswap Token List and Upload to S3

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  S3_BUCKET_NAME: static.cx.metamask.io
  S3_PATH: metamask-uniswap-tokenlist.json

jobs:
  generate-uniswap-list:
    runs-on: ubuntu-latest
    environment: generate-uniswap-list
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '16'

      - name: Generate Uniswap standard token list
        run: node generate-multichain-uniswap-standard-list.js

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ vars.S3_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          echo "Uploading tokenlist to S3..."
          aws s3 cp metamask-uniswap-tokenlist.json s3://${{ env.S3_BUCKET_NAME }}/${{ env.S3_PATH }} --cache-control "max-age=3600"
          echo "Upload complete"
